GameController = {} --estos comentarios son para mi tonto ass ( lo siento, cuando lo tengamos que entregar lo borrare) :3. AQUI HAY UNATABLA

GameController.score = 0
GameController.ScoreMultiplier=1


function GameController.get_score()
	return GameController.score
end

function GameController.update_score(amount)
	GameController.score = GameController.score + amount
	print(GameController.score)
end

return GameController