GameController = {}

GameController.score = 0
GameController.ScoreMultiplier=1


function GameController.get_score()
	return GameController.score
end

function GameController.update_score(amount)
	GameController.score = GameController.score + amount
	print(GameController.score)
	if message_id == hash("Buy") then
		GameController.score=GameController.score-2
		self:Buy()
	end
end

return GameController