function init(self)
	msg.post(".", "acquire_input_focus")  -- Asegúrate de que el objeto puede recibir eventos de entrada
end

function on_message(self, message_id, message, sender)
	if message_id == hash("clicked") then
		ButtonClicked()
	end
end

function ButtonClicked(self)
	-- Lógica específica para cuando el objeto es clicado
	print("¡BOTON!")
	-- Agrega la lógica que desees realizar al hacer clic en este objeto
	GameController.update_score(1*GameController.ScoreMultiplier)
end